#escape seq
print("hellow \"world\" world")
print("line A\n line B\n line c")
print("name \t Ashish")
print("name  Ashish\\")
print("name  Ashish\\\\")
print("hell\bo")
print("line a \\n Line B")
print("line a \\t Line B")
print("\\\"\\\'")
print("this is \\\\ double blackslash")
print("this is /\\/\\/\\/\\ double blackslash")
print("he is \t awesome ")
print("\\\" \\n \\t \\\' ")