a=10
b=20
print("a>b",a>b)
print("a>=b",a>=b)
print("a<b",a<b)
print("a<=b",a<=b)
print("*******************************************")
a="durga"
b="durga"
print("a>b",a>b)
print("a>=b",a>=b)
print("a<b",a<b)
print("a<=b",a<=b)
print("*******************************************")
print(True>True)
print(True>=True)
print(10>True)
print(False>True)
print(10>'durga')