print("**********Employee Information*************")
eno=int(input("EnterEmployee no:"))
ename=(input("EnterEmployee name:"))
esal=float(input("EnterEmployee salary:"))
eaddr=(input("EnterEmployee Address:"))
married=bool(input("Employee is Married?[True|False ]:"))
print("Please confirm information")
print("employee No:",eno)
print("employee Name:",ename)
print("employee Salary:",esal)
print("employee Address:",eaddr)
print("employee Married?:",married)